# Generated by Django 6.0.2 on 2026-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_weight",
            field=models.FloatField(blank=True, help_text="Weight in kg", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.FloatField(blank=True, help_text="Height in cm", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="target_weight",
            field=models.FloatField(
                blank=True, help_text="Target weight in kg", null=True
            ),
        ),
    ]
