# Generated by Django 6.0.2 on 2026-02-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_age_user_current_weight_user_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fitness_level",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
