# Generated by Django 6.0.2 on 2026-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dietlog_weightlog_workoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('difficulty', models.CharField(max_length=20)),
                ('exercises', models.JSONField(default=list)),
            ],
        ),
    ]
