# Generated by Django 5.0.1 on 2026-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_defaultworkout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customworkout",
            options={
                "verbose_name": "Custom Workout",
                "verbose_name_plural": "Custom Workouts",
            },
        ),
        migrations.AlterModelOptions(
            name="defaultworkout",
            options={
                "verbose_name": "Default Workout",
                "verbose_name_plural": "Default Workouts",
            },
        ),
        migrations.AlterModelOptions(
            name="workout",
            options={
                "verbose_name": "Workout Template",
                "verbose_name_plural": "Workout Templates",
            },
        ),
        migrations.AlterField(
            model_name="customworkout",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="defaultworkout",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dietlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="weightlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
